In [39]:
import pandas as pd
import numpy as np

In [8]:
sample = pd.read_csv('appledaily_hk_20160901', header = None, parse_dates = [0])
sample.columns = ['time','id1','location','name','user','type1','type2','type3','type4','ind','reading','device','from',
                 'location2','view']
# reset index as time
sample1 = sample.set_index('time')

In [9]:

sample

,time,id1,location,name,user,type1,type2,type3,type4,ind,reading,device,from,location2,view
0,2016-09-01 08:22:47,a24196ade658f81f92b10a7e5baa25cb,HK,Apple Daily,55571386,US,NEWS,HOMEPAGE,MOSTHIT,0,REALTIME,Android,PUSH,HK,PAGEVIEW
1,2016-09-01 01:13:12,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,NEWS,HOMEPAGE,MOSTHIT,0,COMBINE,Android,0,TH,PAGEVIEW
2,2016-09-01 01:13:16,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,LOCALNEWS,LOCALNEWS,HIGHLIGHT,0,REALTIME,Android,0,TH,PAGEVIEW
3,2016-09-01 01:13:22,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,NEWS,NEWS,ALL,0,REALTIME,Android,LATEST,TH,PAGEVIEW
4,2016-09-01 01:15:56,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,LOCALNEWS,LOCALNEWS,LOCALNEWS,0,0,REALTIME,Android,LATEST,TH,PAGEVIEW
5,2016-09-01 13:36:26,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,NEWS,HOMEPAGE,MOSTHIT,0,COMBINE,Android,0,TH,PAGEVIEW
6,2016-09-01 13:36:56,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,55582645,ENTERTAINMENT,NEWS,HOMEPAGE,MOSTHIT,0,REALTIME,Android,0,TH,PAGEVIEW
7,2016-09-01 13:36:57,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,NEWS,HOMEPAGE,MOSTHIT,0,COMBINE,Android,0,TH,PAGEVIEW
8,2016-09-01 13:38:47,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,55581809,LIFE,NEWS,HOMEPAGE,MOSTHIT,0,REALTIME,Android,0,TH,PAGEVIEW
9,2016-09-01 13:40:23,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,NEWS,HOMEPAGE,MOSTHIT,0,COMBINE,Android,0,TH,PAGEVIEW
10,2016-09-01 13:40:37,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,55583533,ENTERTAINMENT,NEWS,HOMEPAGE,MOSTHIT,0,REALTIME,Android,0,TH,PAGEVIEW
11,2016-09-01 13:43:23,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,NEWS,HOMEPAGE,MOSTHIT,0,COMBINE,Android,0,TH,PAGEVIEW
12,2016-09-01 13:43:59,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,423654,ENTERTAINMENT,NEWS,HOMEPAGE,MOSTHIT,0,REALTIME,Android,0,TH,PAGEVIEW
13,2016-09-01 13:45:10,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,NEWS,HOMEPAGE,MOSTHIT,0,COMBINE,Android,0,TH,PAGEVIEW
14,2016-09-01 13:46:01,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,LOCALNEWS,LOCALNEWS,HIGHLIGHT,0,REALTIME,Android,0,TH,PAGEVIEW
15,2016-09-01 13:46:59,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,LOCALNEWS,BREAKINGNEWS,BREAKINGNEWS,0,0,REALTIME,Android,LATEST,TH,PAGEVIEW
16,2016-09-01 13:50:14,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,ENTERTAINMENT,ENTERTAINMENT,ENTERTAINMENT,0,0,REALTIME,Android,LATEST,TH,PAGEVIEW
17,2016-09-01 13:50:46,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,55584152,ENTERTAINMENT,ENTERTAINMENT,ENTERTAINMENT,0,0,REALTIME,Android,0,TH,PAGEVIEW
18,2016-09-01 13:51:47,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,ENTERTAINMENT,ENTERTAINMENT,ENTERTAINMENT,0,0,REALTIME,Android,LATEST,TH,PAGEVIEW
19,2016-09-01 13:52:16,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,55583859,ENTERTAINMENT,ENTERTAINMENT,ENTERTAINMENT,0,0,REALTIME,Android,0,TH,PAGEVIEW
20,2016-09-01 13:53:21,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,ENTERTAINMENT,ENTERTAINMENT,ENTERTAINMENT,0,0,REALTIME,Android,LATEST,TH,PAGEVIEW
21,2016-09-01 13:57:20,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,55581451,ENTERTAINMENT,ENTERTAINMENT,ENTERTAINMENT,0,0,REALTIME,Android,0,TH,PAGEVIEW
22,2016-09-01 13:58:12,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,ENTERTAINMENT,ENTERTAINMENT,ENTERTAINMENT,0,0,REALTIME,Android,LATEST,TH,PAGEVIEW
23,2016-09-01 18:06:07,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,NEWS,HOMEPAGE,MOSTHIT,0,COMBINE,Android,0,TH,PAGEVIEW
24,2016-09-01 18:06:33,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,55583886,ENTERTAINMENT,NEWS,HOMEPAGE,MOSTHIT,0,REALTIME,Android,0,TH,PAGEVIEW
25,2016-09-01 18:06:54,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,NEWS,HOMEPAGE,MOSTHIT,0,COMBINE,Android,0,TH,PAGEVIEW
26,2016-09-01 18:07:29,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,55583210,SPORTS,NEWS,HOMEPAGE,MOSTHIT,0,REALTIME,Android,0,TH,PAGEVIEW
27,2016-09-01 18:07:30,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,NEWS,HOMEPAGE,MOSTHIT,0,COMBINE,Android,0,TH,PAGEVIEW
28,2016-09-01 18:07:40,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,55583686,ENTERTAINMENT,NEWS,HOMEPAGE,MOSTHIT,0,REALTIME,Android,0,TH,PAGEVIEW
29,2016-09-01 18:09:41,056b80ec0b43d90e129017a23ce618d6,HK,Apple Daily,0,NEWS,NEWS,HOMEPAGE,MOSTHIT,0,COMBINE,Android,0,TH,PAGEVIEW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35660600,2016-09-01 23:58:38,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,55587303,ENTERTAINMENT,ENTERTAINMENT,0,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW
35660601,2016-09-01 23:58:44,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,19755761,ENTERTAINMENT,ENTERTAINMENT,0,0,0,DAILY,Mobile Web,0,HK,PAGEVIEW
35660602,2016-09-01 23:58:44,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,19459799,ENTERTAINMENT,ENTERTAINMENT,0,0,0,DAILY,FBIA,FBIA,HK,PAGEVIEW
35660603,2016-09-01 23:58:44,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,19459799,ENTERTAINMENT,ENTERTAINMENT,0,0,0,DAILY,FBIA,FBIA,HK,PAGEVIEW
35660604,2016-09-01 23:58:49,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,HOMEPAGE,NEWS,HOMEPAGE,0,0,0,Mobile Web,0,HK,PAGEVIEW
35660605,2016-09-01 23:58:52,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,19459799,ENTERTAINMENT,ENTERTAINMENT,0,0,0,DAILY,FBIA,FBIA,MO,PAGEVIEW
35660606,2016-09-01 23:58:53,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,LOCALNEWS,LOCALNEWS,0,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW
35660607,2016-09-01 23:58:59,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,423197,FINANCE,NEXTMAG,NEXTMAG,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW
35660608,2016-09-01 23:59:00,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,55586841,LOCALNEWS,LOCALNEWS,0,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW
35660609,2016-09-01 23:59:00,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,19459799,ENTERTAINMENT,ENTERTAINMENT,0,0,0,DAILY,FBIA,FBIA,HK,PAGEVIEW
35660610,2016-09-01 23:59:01,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,19756535,LOCALNEWS,LOCALNEWS,0,0,0,DAILY,Mobile Web,0,HK,PAGEVIEW
35660611,2016-09-01 23:59:07,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,55587395,LOCALNEWS,LOCALNEWS,0,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW
35660612,2016-09-01 23:59:16,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,19459799,ENTERTAINMENT,ENTERTAINMENT,0,0,0,DAILY,FBIA,FBIA,HK,PAGEVIEW
35660613,2016-09-01 23:59:18,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,US,US,SF,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW
35660614,2016-09-01 23:59:20,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,PRCTWNEWS,PRCTWNEWS,0,0,0,DAILY,Mobile Web,0,HK,PAGEVIEW
35660615,2016-09-01 23:59:20,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,55587385,LOCALNEWS,LOCALNEWS,0,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW
35660616,2016-09-01 23:59:23,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,LOCALNEWS,LOCALNEWS,0,0,0,DAILY,Mobile Web,0,HK,PAGEVIEW
35660617,2016-09-01 23:59:24,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,MAGAZINE,MAGAZINE,HOMEPAGE,0,0,MAGAZINE,Mobile Web,0,HK,PAGEVIEW
35660618,2016-09-01 23:59:29,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,53255592,ENTERTAINMENT,ENTERTAINMENT,ENTERTAINMENT,0,0,REALTIME,Web,UNDEFINED,TW,PAGEVIEW
35660619,2016-09-01 23:59:29,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,ENTERTAINMENT,ENTERTAINMENT,0,0,0,DAILY,Mobile Web,0,HK,PAGEVIEW
35660620,2016-09-01 23:59:30,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,US,US,LA,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW
35660621,2016-09-01 23:59:33,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,NEWS,DVCHANNEL,LOCALNEWS,0,0,REALTIME,Web,UNDEFINED,HK,PAGEVIEW
35660622,2016-09-01 23:59:34,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,19756535,POLITICS,LOCALNEWS,COLUMNIST,0,0,DAILY,Web,UNDEFINED,US,PAGEVIEW
35660623,2016-09-01 23:59:39,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,55581132,FOOD,ETW,ETW,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW
35660624,2016-09-01 23:59:41,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,US,US,NY,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW
35660625,2016-09-01 23:59:43,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,55580980,LIFE,LIFE,0,0,0,REALTIME,Web,UNDEFINED,HK,PAGEVIEW
35660626,2016-09-01 23:59:45,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,HOMEPAGE,NEWS,HOMEPAGE,0,0,0,Mobile Web,0,HK,PAGEVIEW
35660627,2016-09-01 23:59:47,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,LOCALNEWS,LOCALNEWS,0,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW
35660628,2016-09-01 23:59:51,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,0,ENTERTAINMENT,ENTERTAINMENT,0,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW
35660629,2016-09-01 23:59:56,d41d8cd98f00b204e9800998ecf8427e,HK,Apple Daily,55585979,ENTERTAINMENT,ENTERTAINMENT,0,0,0,REALTIME,Mobile Web,0,HK,PAGEVIEW

In [17]:
# 1. Counting number of lines every minute
sample2 = sample1.resample('1T', how = {'id1':'count'})
sample2

                       id1
time
2016-09-01 00:00:00  24290
2016-09-01 00:01:00  24611
2016-09-01 00:02:00  24283
2016-09-01 00:03:00  23887
2016-09-01 00:04:00  24171
2016-09-01 00:05:00  24244
2016-09-01 00:06:00  24185
2016-09-01 00:07:00  24002
2016-09-01 00:08:00  24675
2016-09-01 00:09:00  23924
2016-09-01 00:10:00  23683
2016-09-01 00:11:00  23612
2016-09-01 00:12:00  22929
2016-09-01 00:13:00  23034
2016-09-01 00:14:00  22744
2016-09-01 00:15:00  22798
2016-09-01 00:16:00  22388
2016-09-01 00:17:00  22379
2016-09-01 00:18:00  21616
2016-09-01 00:19:00  21869
2016-09-01 00:20:00  21936
2016-09-01 00:21:00  22107
2016-09-01 00:22:00  22691
2016-09-01 00:23:00  23110
2016-09-01 00:24:00  22524
2016-09-01 00:25:00  22621
2016-09-01 00:26:00  21812
2016-09-01 00:27:00  21033
2016-09-01 00:28:00  20715
2016-09-01 00:29:00  20870
...                    ...
2016-09-01 23:31:00  28211
2016-09-01 23:32:00  27836
2016-09-01 23:33:00  28578
2016-09-01 23:34:00  28328
2016-09-01 23:35:00  28387
2016-09-01 23:36:00  29145
2016-09-01 23:37:00  28971
2016-09-01 23:38:00  28388
2016-09-01 23:39:00  27931
2016-09-01 23:40:00  28119
2016-09-01 23:41:00  28010
2016-09-01 23:42:00  27867
2016-09-01 23:43:00  27899
2016-09-01 23:44:00  27974
2016-09-01 23:45:00  27396
2016-09-01 23:46:00  26800
2016-09-01 23:47:00  27062
2016-09-01 23:48:00  27216
2016-09-01 23:49:00  26608
2016-09-01 23:50:00  27172
2016-09-01 23:51:00  26365
2016-09-01 23:52:00  25918
2016-09-01 23:53:00  25751
2016-09-01 23:54:00  25401
2016-09-01 23:55:00  25445
2016-09-01 23:56:00  24335
2016-09-01 23:57:00  24591
2016-09-01 23:58:00  24389
2016-09-01 23:59:00  24339
2016-09-02 00:00:00    403

[1441 rows x 1 columns]

In [23]:
# 2. Counting number of unique id1 every minute
sample3 = sample1.drop_duplicates(subset = {'id1'})
sample3 = sample3.resample('1T', how = {'id1':'count'})
sample3

                       id1
time
2016-09-01 00:00:00  12615
2016-09-01 00:01:00   6528
2016-09-01 00:02:00   4353
2016-09-01 00:03:00   3567
2016-09-01 00:04:00   3205
2016-09-01 00:05:00   3105
2016-09-01 00:06:00   2810
2016-09-01 00:07:00   2906
2016-09-01 00:08:00   2846
2016-09-01 00:09:00   2655
2016-09-01 00:10:00   2546
2016-09-01 00:11:00   2639
2016-09-01 00:12:00   2468
2016-09-01 00:13:00   2415
2016-09-01 00:14:00   2355
2016-09-01 00:15:00   2393
2016-09-01 00:16:00   2375
2016-09-01 00:17:00   2231
2016-09-01 00:18:00   2284
2016-09-01 00:19:00   2238
2016-09-01 00:20:00   2218
2016-09-01 00:21:00   2324
2016-09-01 00:22:00   2366
2016-09-01 00:23:00   2326
2016-09-01 00:24:00   2278
2016-09-01 00:25:00   2248
2016-09-01 00:26:00   2199
2016-09-01 00:27:00   2123
2016-09-01 00:28:00   1912
2016-09-01 00:29:00   2043
...                    ...
2016-09-01 23:31:00   1278
2016-09-01 23:32:00   1363
2016-09-01 23:33:00   1360
2016-09-01 23:34:00   1303
2016-09-01 23:35:00   1389
2016-09-01 23:36:00   1430
2016-09-01 23:37:00   1331
2016-09-01 23:38:00   1321
2016-09-01 23:39:00   1322
2016-09-01 23:40:00   1301
2016-09-01 23:41:00   1325
2016-09-01 23:42:00   1227
2016-09-01 23:43:00   1231
2016-09-01 23:44:00   1230
2016-09-01 23:45:00   1297
2016-09-01 23:46:00   1210
2016-09-01 23:47:00   1276
2016-09-01 23:48:00   1270
2016-09-01 23:49:00   1273
2016-09-01 23:50:00   1222
2016-09-01 23:51:00   1187
2016-09-01 23:52:00   1141
2016-09-01 23:53:00   1244
2016-09-01 23:54:00   1137
2016-09-01 23:55:00   1162
2016-09-01 23:56:00   1174
2016-09-01 23:57:00   1117
2016-09-01 23:58:00   1143
2016-09-01 23:59:00   1137
2016-09-02 00:00:00     21

[1441 rows x 1 columns]

In [48]:
# 3. pivoting table by type1
sample4 = sample.pivot_table(index = {'time'}, columns = {'type1'},aggfunc = 'count', fill_value = 0)

                    id1                                            \
type1                 0 ADULT ANIMAL ARCHIVE ARTCHIVE AUTO BEAUTY
time
2016-09-01 00:00:00   2     0      0       0        0    0      0
2016-09-01 00:00:01   1     0      0       1        0    0      0
2016-09-01 00:00:02   3     0      0       0        0    0      1
2016-09-01 00:00:03   0     0      0       0        0    1      0
2016-09-01 00:00:04   0     0      0       1        0    0      0
2016-09-01 00:00:05   2     0      0       0        0    0      0
2016-09-01 00:00:06   1     0      0       0        0    2      0
2016-09-01 00:00:07   2     0      0       0        0    0      0
2016-09-01 00:00:08   0     0      0       1        0    0      0
2016-09-01 00:00:09   1     0      0       1        0    0      0
2016-09-01 00:00:10   0     0      0       0        0    0      0
2016-09-01 00:00:11   1     0      0       0        0    0      0
2016-09-01 00:00:12   0     0      0       1        0    0      0
2016-09-01 00:00:13   0     0      0       0        0    0      0
2016-09-01 00:00:14   0     0      0       0        0    0      0
2016-09-01 00:00:15   0     0      0       1        0    0      0
2016-09-01 00:00:16   2     0      0       0        0    0      0
2016-09-01 00:00:17   2     0      0       1        0    0      0
2016-09-01 00:00:18   1     0      0       1        0    0      0
2016-09-01 00:00:19   1     0      0       0        0    0      1
2016-09-01 00:00:20   1     0      0       0        0    0      0
2016-09-01 00:00:21   1     0      0       1        0    0      0
2016-09-01 00:00:22   3     0      0       0        0    0      0
2016-09-01 00:00:23   1     0      0       0        0    0      0
2016-09-01 00:00:24   2     0      0       0        0    0      0
2016-09-01 00:00:25   4     0      0       0        0    1      0
2016-09-01 00:00:26   0     0      0       1        0    0      0
2016-09-01 00:00:27   0     0      0       0        0    0      0
2016-09-01 00:00:28   0     0      0       0        0    1      0
2016-09-01 00:00:29   1     0      0       0        0    0      0
...                  ..   ...    ...     ...      ...  ...    ...
2016-09-01 23:59:31   0     0      0       0        0    1      0
2016-09-01 23:59:32   4     0      0       1        0    0      0
2016-09-01 23:59:33   2     0      0       0        0    1      1
2016-09-01 23:59:34   1     0      0       0        0    0      0
2016-09-01 23:59:35   1     0      0       2        0    0      0
2016-09-01 23:59:36   1     0      0       0        0    0      0
2016-09-01 23:59:37   2     0      0       0        0    0      0
2016-09-01 23:59:38   1     0      0       0        0    0      0
2016-09-01 23:59:39   1     0      0       0        0    0      0
2016-09-01 23:59:40   3     0      0       0        0    0      0
2016-09-01 23:59:41   2     0      0       0        0    0      0
2016-09-01 23:59:42   2     0      0       0        0    0      0
2016-09-01 23:59:43   3     0      0       0        0    1      1
2016-09-01 23:59:44   1     0      0       1        0    2      0
2016-09-01 23:59:45   0     0      0       1        0    1      0
2016-09-01 23:59:46   1     0      0       0        0    0      0
2016-09-01 23:59:47   1     0      0       0        0    0      0
2016-09-01 23:59:48   4     0      0       0        0    0      0
2016-09-01 23:59:49   2     0      0       0        0    1      0
2016-09-01 23:59:50   1     0      0       1        0    0      0
2016-09-01 23:59:51   5     0      0       0        0    0      0
2016-09-01 23:59:52   1     0      0       1        0    1      0
2016-09-01 23:59:53   1     0      0       0        0    4      0
2016-09-01 23:59:54   4     0      0       0        0    0      0
2016-09-01 23:59:55   1     1      0       0        0    1      0
2016-09-01 23:59:56   4     0      0       0        0    0      0
2016-09-01 23:59:57   1     0      0       0        0    1      0
2016-09-01 23:59:58   0     0      0       0        0    0      0
2016-09-01 23:59:59   1     0      0       0        0    0      0
2016-09-02 00:00:00   1     0      0       0        0    0      0

                                                  ...      view         \
type1               BREAKINGNEWS BUSINESS CAMPUS  ...  SETTINGS SOCCER
time                                              ...
2016-09-01 00:00:00           20        0      0  ...         0      0
2016-09-01 00:00:01           17        0      0  ...         0      0
2016-09-01 00:00:02           24        0      0  ...         0      0
2016-09-01 00:00:03           20        0      0  ...         0      0
2016-09-01 00:00:04           21        0      0  ...         0      0
2016-09-01 00:00:05           24        0      0  ...         0      0
2016-09-01 00:00:06           23        0      0  ...         0      0
2016-09-01 00:00:07           19        0      0  ...         0      0
2016-09-01 00:00:08           16        0      0  ...         0      0
2016-09-01 00:00:09           19        0      0  ...         0      2
2016-09-01 00:00:10           21        0      0  ...         0      1
2016-09-01 00:00:11           18        0      0  ...         0      0
2016-09-01 00:00:12           17        0      0  ...         0      1
2016-09-01 00:00:13           15        0      0  ...         1      0
2016-09-01 00:00:14           13        0      0  ...         0      0
2016-09-01 00:00:15           13        0      0  ...         0      0
2016-09-01 00:00:16           17        0      0  ...         0      0
2016-09-01 00:00:17           22        0      0  ...         0      0
2016-09-01 00:00:18            9        0      0  ...         0      0
2016-09-01 00:00:19           20        0      0  ...         0      0
2016-09-01 00:00:20           14        0      0  ...         0      0
2016-09-01 00:00:21           15        0      0  ...         0      0
2016-09-01 00:00:22           14        0      0  ...         0      0
2016-09-01 00:00:23           13        0      0  ...         0      1
2016-09-01 00:00:24           21        0      0  ...         0      0
2016-09-01 00:00:25           19        0      0  ...         0      0
2016-09-01 00:00:26           18        0      0  ...         0      1
2016-09-01 00:00:27           17        0      0  ...         1      0
2016-09-01 00:00:28           16        0      0  ...         0      0
2016-09-01 00:00:29           12        0      0  ...         0      0
...                          ...      ...    ...  ...       ...    ...
2016-09-01 23:59:31           11        0      0  ...         0      0
2016-09-01 23:59:32           15        0      0  ...         0      0
2016-09-01 23:59:33           11        0      0  ...         0      0
2016-09-01 23:59:34           17        0      0  ...         0      0
2016-09-01 23:59:35           22        0      0  ...         0      0
2016-09-01 23:59:36           16        0      0  ...         0      0
2016-09-01 23:59:37           17        0      0  ...         1      0
2016-09-01 23:59:38           17        0      0  ...         0      0
2016-09-01 23:59:39           13        0      0  ...         0      0
2016-09-01 23:59:40           12        0      0  ...         0      0
2016-09-01 23:59:41           21        0      0  ...         0      0
2016-09-01 23:59:42           15        0      0  ...         0      0
2016-09-01 23:59:43           10        0      0  ...         0      0
2016-09-01 23:59:44           15        0      0  ...         0      0
2016-09-01 23:59:45           15        0      0  ...         0      0
2016-09-01 23:59:46           11        0      0  ...         0      0
2016-09-01 23:59:47           10        0      0  ...         0      1
2016-09-01 23:59:48           18        0      0  ...         0      0
2016-09-01 23:59:49           16        0      0  ...         0      2
2016-09-01 23:59:50            9        0      0  ...         0      1
2016-09-01 23:59:51           19        0      0  ...         0      0
2016-09-01 23:59:52           10        0      0  ...         0      0
2016-09-01 23:59:53            5        0      0  ...         1      1
2016-09-01 23:59:54           14        0      0  ...         0      0
2016-09-01 23:59:55           13        0      0  ...         0      0
2016-09-01 23:59:56           14        0      0  ...         1      0
2016-09-01 23:59:57           12        0      0  ...         0      0
2016-09-01 23:59:58           19        0      0  ...         0      0
2016-09-01 23:59:59           12        0      0  ...         0      0
2016-09-02 00:00:00           16        0      0  ...         0      0


type1               SPECIAL SPORTS TECH TOPIC TRAVEL  US VOICE WEIRD
time
2016-09-01 00:00:00       0      9    0     0      2   0     0     0
2016-09-01 00:00:01       0     15    2     0      1   3     0     0
2016-09-01 00:00:02       0      8    0     0      0   2     0     0
2016-09-01 00:00:03       0     17    0     0      0   3     0     0
2016-09-01 00:00:04       0     23    1     0      0   3     0     0
2016-09-01 00:00:05       0     17    2     0      0   3     0     0
2016-09-01 00:00:06       0     13    0     0      0   3     0     0
2016-09-01 00:00:07       0     24    0     0      1   2     0     0
2016-09-01 00:00:08       0     15    0     0      0   2     0     0
2016-09-01 00:00:09       0     12    0     0      0   5     0     0
2016-09-01 00:00:10       0     13    1     0      0   3     0     0
2016-09-01 00:00:11       0     14    1     0      1   5     0     0
2016-09-01 00:00:12       0     21    2     0      1   1     0     0
2016-09-01 00:00:13       0     13    0     0      0   3     0     0
2016-09-01 00:00:14       0     12    0     0      0   1     0     0
2016-09-01 00:00:15       0     18    1     0      0   1     0     0
2016-09-01 00:00:16       0     15    1     0      1   2     0     0
2016-09-01 00:00:17       0     16    1     0      1   3     0     0
2016-09-01 00:00:18       0     17    0     0      0   0     0     0
2016-09-01 00:00:19       0     15    0     0      0   2     0     0
2016-09-01 00:00:20       0     15    0     0      0   4     0     0
2016-09-01 00:00:21       1     17    0     0      2   6     0     0
2016-09-01 00:00:22       0     12    3     0      0   2     0     0
2016-09-01 00:00:23       0     12    0     0      1   2     0     0
2016-09-01 00:00:24       0     12    1     0      0   5     0     0
2016-09-01 00:00:25       0     15    1     0      1   1     0     0
2016-09-01 00:00:26       0     15    0     0      0   2     0     0
2016-09-01 00:00:27       0     10    0     0      2   4     0     0
2016-09-01 00:00:28       0     14    1     0      0   4     0     0
2016-09-01 00:00:29       0     17    2     0      1   5     0     0
...                     ...    ...  ...   ...    ...  ..   ...   ...
2016-09-01 23:59:31       0     11    0     0      0   6     0     0
2016-09-01 23:59:32       0     11    0     0      0   6     0     0
2016-09-01 23:59:33       0     16    0     0      0   4     0     0
2016-09-01 23:59:34       1     19    0     0      0   4     0     0
2016-09-01 23:59:35       0     15    1     0      0   3     0     0
2016-09-01 23:59:36       0     20    0     0      0  11     0     0
2016-09-01 23:59:37       0     12    0     0      1   2     0     0
2016-09-01 23:59:38       2     11    0     0      0   0     0     0
2016-09-01 23:59:39       0     15    0     0      0   5     0     0
2016-09-01 23:59:40       1     14    0     0      0   4     0     0
2016-09-01 23:59:41       0     14    0     0      0   4     0     0
2016-09-01 23:59:42       0     11    0     0      0   7     0     0
2016-09-01 23:59:43       0     17    0     0      0   6     0     0
2016-09-01 23:59:44       0      9    0     0      0   7     0     0
2016-09-01 23:59:45       3     15    0     0      1   5     0     0
2016-09-01 23:59:46       1     10    1     0      2   4     0     0
2016-09-01 23:59:47       2     13    1     0      0   6     0     0
2016-09-01 23:59:48       0     15    0     0      0   1     0     0
2016-09-01 23:59:49       1     16    0     0      0   6     0     0
2016-09-01 23:59:50       0     16    0     0      0   7     0     0
2016-09-01 23:59:51       0     22    0     0      0   4     0     0
2016-09-01 23:59:52       0     15    1     0      1   3     0     0
2016-09-01 23:59:53       0     13    0     0      1   9     0     0
2016-09-01 23:59:54       1     13    1     0      0   5     0     0
2016-09-01 23:59:55       0     19    0     0      0   5     0     0
2016-09-01 23:59:56       0     21    0     0      0   4     0     0
2016-09-01 23:59:57       0     12    0     0      0   4     0     0
2016-09-01 23:59:58       2     13    0     0      0   6     0     0
2016-09-01 23:59:59       0     16    0     0      1   5     0     0
2016-09-02 00:00:00       0     18    0     0      0   3     0     0

[86401 rows x 845 columns]

In [49]:
sample5 = sample4.resample('1T', how = 'sum')
sample5

                     id1                                            \
type1                  0 ADULT ANIMAL ARCHIVE ARTCHIVE AUTO BEAUTY
time
2016-09-01 00:00:00   77     0      0      13        0    8      4
2016-09-01 00:01:00  100     0      1      10        0    7      3
2016-09-01 00:02:00  101     0      0      19        0    8      2
2016-09-01 00:03:00   85     0      1      14        0   10      2
2016-09-01 00:04:00  102     0      1      13        0    5      6
2016-09-01 00:05:00   88     0      1      11        0    6      5
2016-09-01 00:06:00  106     0      0      10        0    9      5
2016-09-01 00:07:00   98     0      0      11        0    4      7
2016-09-01 00:08:00  100     0      0      10        0    7      5
2016-09-01 00:09:00   96     0      0      16        0    5      2
2016-09-01 00:10:00   74     0      0      13        0    6      7
2016-09-01 00:11:00   78     0      0      19        0   10      1
2016-09-01 00:12:00   97     0      0      23        0   10      6
2016-09-01 00:13:00   91     1      0      17        0    5      6
2016-09-01 00:14:00   90     0      0      21        0    3      6
2016-09-01 00:15:00   82     0      0      25        0   10      6
2016-09-01 00:16:00   82     0      1       7        0   12      3
2016-09-01 00:17:00   79     0      0      19        0    7      2
2016-09-01 00:18:00   53     0      0      24        0   11      4
2016-09-01 00:19:00   49     0      0      17        0    8      6
2016-09-01 00:20:00   67     0      0       7        0    6      2
2016-09-01 00:21:00   81     0      0       9        0    5      1
2016-09-01 00:22:00  140     0      0      12        0    5      3
2016-09-01 00:23:00  209     0      0       8        0   12      4
2016-09-01 00:24:00   84     0      0       6        0   14      9
2016-09-01 00:25:00   75     0      0       6        0    7      4
2016-09-01 00:26:00   94     0      0       7        0    5      2
2016-09-01 00:27:00   80     0      0       9        0    5      2
2016-09-01 00:28:00   81     0      0       7        0    7      3
2016-09-01 00:29:00   61     0      0       9        0    7      1
...                  ...   ...    ...     ...      ...  ...    ...
2016-09-01 23:31:00   76    10      0      13        0   25      1
2016-09-01 23:32:00   77     3      0      15        0   24      2
2016-09-01 23:33:00   94     4      1      14        0   25      6
2016-09-01 23:34:00  103     8      0      20        0   31      5
2016-09-01 23:35:00  101     3      0      20        0   34      2
2016-09-01 23:36:00  111     6      0      24        0   36      4
2016-09-01 23:37:00   92     2      0      25        0   18      5
2016-09-01 23:38:00  113     5      0      20        0   24      3
2016-09-01 23:39:00   76     8      0      17        0   31      2
2016-09-01 23:40:00   93     4      0      14        0   27      5
2016-09-01 23:41:00  104    10      0      10        0   30      3
2016-09-01 23:42:00   89     8      0      13        0   31      1
2016-09-01 23:43:00   92     5      0      15        0   25      7
2016-09-01 23:44:00   97     7      0      16        0   22      0
2016-09-01 23:45:00   82     8      0       9        0   40      4
2016-09-01 23:46:00   88     5      0      23        0   26      6
2016-09-01 23:47:00   95     5      0      15        0   26      3
2016-09-01 23:48:00   90     8      1      12        0   35      4
2016-09-01 23:49:00   86     7      0      17        0   40      6
2016-09-01 23:50:00   87     6      0      13        0   19      2
2016-09-01 23:51:00   87     9      0      15        0   23      5
2016-09-01 23:52:00  102     6      0      19        0   29      3
2016-09-01 23:53:00  107     8      0      17        0   28      2
2016-09-01 23:54:00  112     5      0      12        0   19      2
2016-09-01 23:55:00  160     8      0      13        0   21      6
2016-09-01 23:56:00   96     6      0      12        0   25      7
2016-09-01 23:57:00  130     6      0      12        0   28      4
2016-09-01 23:58:00  122     8      0      13        0   35      5
2016-09-01 23:59:00  111     3      0      14        0   27      6
2016-09-02 00:00:00    1     0      0       0        0    0      0

                                                  ...      view         \
type1               BREAKINGNEWS BUSINESS CAMPUS  ...  SETTINGS SOCCER
time                                              ...
2016-09-01 00:00:00         1156        0      0  ...         6     14
2016-09-01 00:01:00         1175        0      0  ...        10     13
2016-09-01 00:02:00         1225        0      0  ...         5     12
2016-09-01 00:03:00         1249        0      0  ...         5     12
2016-09-01 00:04:00         1219        0      0  ...         8     16
2016-09-01 00:05:00         1329        0      0  ...         6      5
2016-09-01 00:06:00         1292        0      0  ...         4     11
2016-09-01 00:07:00         1356        0      0  ...         3     11
2016-09-01 00:08:00         1320        2      0  ...         4      8
2016-09-01 00:09:00         1247        0      0  ...        16     14
2016-09-01 00:10:00         1256        0      0  ...         6      9
2016-09-01 00:11:00         1263        0      0  ...         2      9
2016-09-01 00:12:00         1206        0      0  ...         4     17
2016-09-01 00:13:00         1237        0      0  ...         6      7
2016-09-01 00:14:00         1278        0      0  ...         3     15
2016-09-01 00:15:00         1250        0      0  ...         3     13
2016-09-01 00:16:00         1235        0      0  ...         4      4
2016-09-01 00:17:00         1247        0      1  ...         3     15
2016-09-01 00:18:00         1133        0      0  ...         6     10
2016-09-01 00:19:00         1149        0      0  ...         6     14
2016-09-01 00:20:00         1147        0      0  ...         9      8
2016-09-01 00:21:00         1192        0      0  ...        11     10
2016-09-01 00:22:00         1208        0      0  ...         4     10
2016-09-01 00:23:00         1270        0      0  ...         6     16
2016-09-01 00:24:00         1192        0      0  ...         4      7
2016-09-01 00:25:00         1158        0      0  ...         4     13
2016-09-01 00:26:00         1042        0      0  ...         3     13
2016-09-01 00:27:00          985        0      1  ...         1     13
2016-09-01 00:28:00          995        0      0  ...        11      8
2016-09-01 00:29:00          966        0      0  ...         5      8
...                          ...      ...    ...  ...       ...    ...
2016-09-01 23:31:00         1219        0      0  ...         8     22
2016-09-01 23:32:00         1242        0      0  ...         9     22
2016-09-01 23:33:00         1208        0      0  ...         7     19
2016-09-01 23:34:00         1091        0      1  ...         8     17
2016-09-01 23:35:00         1047        0      0  ...         6     19
2016-09-01 23:36:00         1067        0      0  ...        14     19
2016-09-01 23:37:00         1077        0      0  ...         7     25
2016-09-01 23:38:00         1005        0      0  ...         6      7
2016-09-01 23:39:00          898        0      0  ...         6      8
2016-09-01 23:40:00          900        0      0  ...         3     11
2016-09-01 23:41:00          866        0      0  ...         1     15
2016-09-01 23:42:00          846        0      1  ...        15     15
2016-09-01 23:43:00          966        0      0  ...         9     12
2016-09-01 23:44:00          922        1      0  ...        13     15
2016-09-01 23:45:00         1014        0      0  ...         6     17
2016-09-01 23:46:00          992        0      0  ...         3     19
2016-09-01 23:47:00         1073        0      0  ...         6     15
2016-09-01 23:48:00         1048        0      0  ...         2     14
2016-09-01 23:49:00         1063        0      0  ...         4     26
2016-09-01 23:50:00         1097        0      0  ...         9     20
2016-09-01 23:51:00         1040        0      0  ...         9     27
2016-09-01 23:52:00         1006        0      0  ...         4     29
2016-09-01 23:53:00          999        0      0  ...         4     27
2016-09-01 23:54:00          894        0      0  ...         7     18
2016-09-01 23:55:00          954        0      0  ...         7     17
2016-09-01 23:56:00          841        0      0  ...         2     17
2016-09-01 23:57:00          851        1      0  ...         8     15
2016-09-01 23:58:00          827        0      0  ...         4     22
2016-09-01 23:59:00          831        0      0  ...         4     10
2016-09-02 00:00:00           16        0      0  ...         0      0


type1               SPECIAL SPORTS TECH TOPIC TRAVEL   US VOICE WEIRD
time
2016-09-01 00:00:00       6    868   35     0     28  156     0     0
2016-09-01 00:01:00      11    825   34     0     26  113     0     0
2016-09-01 00:02:00       5    803   30     1     25  120     0     0
2016-09-01 00:03:00       7    782   39     0     19  137     0     0
2016-09-01 00:04:00      14    802   27     0     26  158     0     0
2016-09-01 00:05:00      16    763   40     0     24  157     0     0
2016-09-01 00:06:00       4    759   47     0     25  153     0     0
2016-09-01 00:07:00      12    754   56     1     24  148     0     0
2016-09-01 00:08:00      15    764   43     0     25  173     0     0
2016-09-01 00:09:00      12    709   42     0     30  111     0     0
2016-09-01 00:10:00      14    763   43     0     29  142     0     0
2016-09-01 00:11:00       8    706   36     0     24  121     0     0
2016-09-01 00:12:00       7    719   33     0     28  109     0     0
2016-09-01 00:13:00       5    748   40     0     26  135     0     0
2016-09-01 00:14:00       5    765   42     0     28  118     0     0
2016-09-01 00:15:00       3    735   19     0     15  136     0     0
2016-09-01 00:16:00       5    735   31     0     14   95     0     0
2016-09-01 00:17:00      19    785   37     0     13   93     0     0
2016-09-01 00:18:00       7    673   33     0     18  104     0     0
2016-09-01 00:19:00       7    717   32     0     22  113     0     0
2016-09-01 00:20:00      14    826   33     0      9  117     0     0
2016-09-01 00:21:00       8    856   40     0     24  102     0     0
2016-09-01 00:22:00      10    883   28     0     17  120     0     0
2016-09-01 00:23:00       6    822   40     0     25  137     0     0
2016-09-01 00:24:00      11    826   36     0     21  144     0     1
2016-09-01 00:25:00      20    818   49     1     22  141     0     0
2016-09-01 00:26:00       6    793   31     0     24  137     0     0
2016-09-01 00:27:00      18    689   40     0     23  124     0     0
2016-09-01 00:28:00       6    650   43     0     24  124     0     0
2016-09-01 00:29:00      14    661   44     0     22  159     0     0
...                     ...    ...  ...   ...    ...  ...   ...   ...
2016-09-01 23:31:00      20   1096   14     0     20  302     0     0
2016-09-01 23:32:00      18   1127    9     1     15  304     0     0
2016-09-01 23:33:00      20   1094   23     0     18  343     0     0
2016-09-01 23:34:00      17   1144   10     0     20  332     0     0
2016-09-01 23:35:00       9   1171   17     0     14  333     0     0
2016-09-01 23:36:00      14   1163   15     0     16  348     0     0
2016-09-01 23:37:00      16   1151    9     0     15  397     0     0
2016-09-01 23:38:00      12   1025   13     0     14  350     0     0
2016-09-01 23:39:00      23   1124    9     0     18  345     0     0
2016-09-01 23:40:00      15   1115   10     0     14  369     0     0
2016-09-01 23:41:00      23   1117   11     0     11  330     0     0
2016-09-01 23:42:00      16   1158   19     0     17  368     0     0
2016-09-01 23:43:00      21   1127   11     0     18  388     0     0
2016-09-01 23:44:00      13   1096   11     0     27  375     0     0
2016-09-01 23:45:00      25   1051    7     0     19  380     0     0
2016-09-01 23:46:00      24   1080   12     0     24  346     0     0
2016-09-01 23:47:00      16   1044    8     0     11  347     0     0
2016-09-01 23:48:00      27   1118   16     0     14  377     0     0
2016-09-01 23:49:00      13   1052   22     0     14  398     0     0
2016-09-01 23:50:00      16   1187   13     0     16  368     0     0
2016-09-01 23:51:00       8   1132    9     0     21  367     0     0
2016-09-01 23:52:00      20   1078   11     0     15  357     0     0
2016-09-01 23:53:00      16   1097   14     0     10  339     0     0
2016-09-01 23:54:00      14   1126   11     0      7  330     0     1
2016-09-01 23:55:00      17   1007   12     0     10  310     0     1
2016-09-01 23:56:00      17    961   15     0      9  333     0     0
2016-09-01 23:57:00      21   1046   15     0     12  354     0     0
2016-09-01 23:58:00      13   1012   10     0     17  322     0     0
2016-09-01 23:59:00      18    944   10     0     15  309     0     0
2016-09-02 00:00:00       0     18    0     0      0    3     0     0

[1441 rows x 845 columns]

In [50]:
# 4. pivoting table by type2
sample6 = sample.pivot_table(index = {'time'}, columns = {'type2'},aggfunc = 'count', fill_value = 0).resample('1T', how = 'sum')
sample6

                     id1                                                  \
type2                  0 BREAKING BREAKINGNEWS CALENDAR COLUMNIST COUPON
time
2016-09-01 00:00:00   49      254         1047        3         6      1
2016-09-01 00:01:00   64      301         1081        8         6      1
2016-09-01 00:02:00   64      291         1128        1         9      1
2016-09-01 00:03:00   59      287         1114        5        14      0
2016-09-01 00:04:00   72      277         1064        5         8      0
2016-09-01 00:05:00   52      231         1066        4         8      0
2016-09-01 00:06:00   71      300         1010        2         3      0
2016-09-01 00:07:00   75      283         1023        1         6      0
2016-09-01 00:08:00   66      276          973        3        14      0
2016-09-01 00:09:00   71      231          879        4         4      0
2016-09-01 00:10:00   57      252          889        1         4      0
2016-09-01 00:11:00   53      217          904        0         7      1
2016-09-01 00:12:00   78      218          931        1         4      0
2016-09-01 00:13:00   73      263          970        0         3      0
2016-09-01 00:14:00   64      279          979        2        24      0
2016-09-01 00:15:00   60      235          909        1         4      0
2016-09-01 00:16:00   58      224         1014        3         1      0
2016-09-01 00:17:00   52      251         1009        1         4      0
2016-09-01 00:18:00   37      241          918        4         2      0
2016-09-01 00:19:00   34      220          889        3         1      1
2016-09-01 00:20:00   46      234          884        3        13      0
2016-09-01 00:21:00   67      256          943        6        13      1
2016-09-01 00:22:00  112      222          970        1        12      0
2016-09-01 00:23:00  174      266          932        0         5      1
2016-09-01 00:24:00   62      229          932        2         9      0
2016-09-01 00:25:00   52      240          954        3         5      0
2016-09-01 00:26:00   69      216          937        1         3      0
2016-09-01 00:27:00   65      202          896        1         5      1
2016-09-01 00:28:00   59      206          909        8        10      0
2016-09-01 00:29:00   41      209          874        4         6      2
...                  ...      ...          ...      ...       ...    ...
2016-09-01 23:31:00   61      215         1159        7         4      0
2016-09-01 23:32:00   59      209         1105        4         2      0
2016-09-01 23:33:00   75      261         1168        2        12      1
2016-09-01 23:34:00   85      251         1135        1        11      1
2016-09-01 23:35:00   92      239         1191        0         7      2
2016-09-01 23:36:00   88      249         1243        4        15      0
2016-09-01 23:37:00   75      237         1179        2        14      0
2016-09-01 23:38:00   93      224         1146        1        10      0
2016-09-01 23:39:00   64      167         1156        0         6      0
2016-09-01 23:40:00   77      191         1174        0         6      0
2016-09-01 23:41:00   92      196         1158        0        11      2
2016-09-01 23:42:00   77      223         1214        8         6      0
2016-09-01 23:43:00   80      184         1226        1         9      2
2016-09-01 23:44:00   85      245         1204        2        13      3
2016-09-01 23:45:00   64      196         1116        2        26      0
2016-09-01 23:46:00   73      186         1064        2        35      0
2016-09-01 23:47:00   81      194         1214        1        20      1
2016-09-01 23:48:00   79      197         1108        1        12      0
2016-09-01 23:49:00   74      194         1107        2         8      0
2016-09-01 23:50:00   70      208         1141        2        14      1
2016-09-01 23:51:00   71      206          985        4         7      0
2016-09-01 23:52:00   86      176         1043        2         4      0
2016-09-01 23:53:00   88      190          984        3         7      1
2016-09-01 23:54:00   86      158          909        3        25      1
2016-09-01 23:55:00  141      168          948        3        14      0
2016-09-01 23:56:00   74      158          927        1        12      3
2016-09-01 23:57:00  117      163          894        4         5      1
2016-09-01 23:58:00  107      177          957        3         9      0
2016-09-01 23:59:00   93      171          981        1         2      1
2016-09-02 00:00:00    1        2           19        0         0      0

                                                            ...        view  \
type2               DVCHANNEL ENTERTAINMENT  ETW FINANCE    ...     NEXTMAG
time                                                        ...
2016-09-01 00:00:00       165          2931   96    1365    ...         158
2016-09-01 00:01:00       175          2948   72    1346    ...         154
2016-09-01 00:02:00       145          3043  109    1330    ...         183
2016-09-01 00:03:00       147          2951   92    1277    ...         147
2016-09-01 00:04:00       140          3100   95    1318    ...         166
2016-09-01 00:05:00       163          3180   82    1281    ...         139
2016-09-01 00:06:00       177          3068   98    1212    ...         180
2016-09-01 00:07:00       144          3255   97    1201    ...         162
2016-09-01 00:08:00       188          3366  102    1288    ...         163
2016-09-01 00:09:00       126          3305  123    1312    ...         176
2016-09-01 00:10:00       147          3279  132    1211    ...         167
2016-09-01 00:11:00       151          3183   80    1184    ...         163
2016-09-01 00:12:00       140          3183   98    1146    ...         149
2016-09-01 00:13:00       145          3362   84    1055    ...         145
2016-09-01 00:14:00       132          3214  106    1093    ...         117
2016-09-01 00:15:00       146          3327   62    1147    ...         168
2016-09-01 00:16:00       124          3226   79    1186    ...         155
2016-09-01 00:17:00       121          3285  102    1208    ...         152
2016-09-01 00:18:00       140          3131  121    1100    ...         155
2016-09-01 00:19:00       157          3244  129    1072    ...         130
2016-09-01 00:20:00       115          3123   91    1114    ...         130
2016-09-01 00:21:00       141          3118   82    1107    ...         124
2016-09-01 00:22:00       133          3281  104    1123    ...         114
2016-09-01 00:23:00       138          3316   97    1147    ...         144
2016-09-01 00:24:00       130          3352   87    1116    ...         141
2016-09-01 00:25:00       148          3238  105    1128    ...         114
2016-09-01 00:26:00       142          3148   82    1103    ...         134
2016-09-01 00:27:00       109          2966   96    1006    ...         126
2016-09-01 00:28:00        91          3048   99     969    ...         145
2016-09-01 00:29:00       113          3004   89    1036    ...         110
...                       ...           ...  ...     ...    ...         ...
2016-09-01 23:31:00       163          4095   98    1437    ...          89
2016-09-01 23:32:00       154          4115  106    1396    ...          88
2016-09-01 23:33:00       136          4148  113    1450    ...          72
2016-09-01 23:34:00       146          4091   88    1486    ...         105
2016-09-01 23:35:00       153          4235  114    1561    ...          83
2016-09-01 23:36:00       160          4163  116    1618    ...          84
2016-09-01 23:37:00       144          4239   98    1554    ...          98
2016-09-01 23:38:00       166          4074  113    1646    ...          84
2016-09-01 23:39:00       167          4065  123    1434    ...          86
2016-09-01 23:40:00       162          3969  113    1497    ...          98
2016-09-01 23:41:00       154          4025   99    1459    ...          93
2016-09-01 23:42:00       143          4117   95    1552    ...          89
2016-09-01 23:43:00       181          4101  113    1601    ...          81
2016-09-01 23:44:00       168          4196  118    1519    ...          93
2016-09-01 23:45:00       134          4145  120    1707    ...          67
2016-09-01 23:46:00       145          4172  101    1549    ...          65
2016-09-01 23:47:00       153          4065  112    1461    ...          68
2016-09-01 23:48:00       153          4133   86    1497    ...          68
2016-09-01 23:49:00       132          3981   77    1434    ...          94
2016-09-01 23:50:00       163          3945   92    1464    ...          83
2016-09-01 23:51:00       180          3895   99    1438    ...          89
2016-09-01 23:52:00       161          3741   83    1503    ...         119
2016-09-01 23:53:00       121          3733   87    1388    ...          67
2016-09-01 23:54:00       144          3662   97    1521    ...          69
2016-09-01 23:55:00       132          3805  103    1578    ...          76
2016-09-01 23:56:00       141          3639   79    1357    ...          77
2016-09-01 23:57:00       111          3656   89    1365    ...          69
2016-09-01 23:58:00       124          3626   88    1340    ...          62
2016-09-01 23:59:00       146          3709   89    1387    ...          76
2016-09-02 00:00:00         5            59    0      20    ...           1

                                                                         \
type2               PRCTWNEWS RACING REPORTDAILY SEARCH SETTING SPECIAL
time
2016-09-01 00:00:00       973    231           6    405      15      26
2016-09-01 00:01:00       911    232           4    368      16      40
2016-09-01 00:02:00       885    226           1    294      13      39
2016-09-01 00:03:00       935    244           1    320       8      30
2016-09-01 00:04:00       915    279           2    364      13      45
2016-09-01 00:05:00       948    279           0    308      15      22
2016-09-01 00:06:00       908    234           0    339      19      32
2016-09-01 00:07:00       876    226           0    268      12      28
2016-09-01 00:08:00       904    251           2    301      17      40
2016-09-01 00:09:00       945    281           0    310      13      41
2016-09-01 00:10:00       988    249           1    281       7      58
2016-09-01 00:11:00      1001    219           0    331      12      60
2016-09-01 00:12:00       928    232           1    240       7      50
2016-09-01 00:13:00       969    254           1    333       5      59
2016-09-01 00:14:00       953    260           2    276      11      46
2016-09-01 00:15:00       905    257           1    245       8      51
2016-09-01 00:16:00       886    195           2    308       5      22
2016-09-01 00:17:00       890    193           1    266      14      31
2016-09-01 00:18:00       912    188           1    224       5      20
2016-09-01 00:19:00       928    230           4    268       6      27
2016-09-01 00:20:00       925    228           2    265      11      37
2016-09-01 00:21:00       862    229           0    239       8      45
2016-09-01 00:22:00      1010    226           0    245      18      31
2016-09-01 00:23:00       984    202           1    278      18      24
2016-09-01 00:24:00       970    165           2    321      10      19
2016-09-01 00:25:00       935    213           0    345      17      46
2016-09-01 00:26:00       920    189           2    274      12      25
2016-09-01 00:27:00       914    165           7    324       5      37
2016-09-01 00:28:00       863    183           1    322      10      38
2016-09-01 00:29:00       906    238           3    310      10      22
...                       ...    ...         ...    ...     ...     ...
2016-09-01 23:31:00      1157    240           1    408      11      49
2016-09-01 23:32:00      1169    301           1    328      16      64
2016-09-01 23:33:00      1195    312           1    362      11      65
2016-09-01 23:34:00      1224    265           2    351       9      64
2016-09-01 23:35:00      1104    261           0    354       7      57
2016-09-01 23:36:00      1163    311           0    373      19      54
2016-09-01 23:37:00      1142    302           0    415      14      37
2016-09-01 23:38:00      1281    275           2    402      15      36
2016-09-01 23:39:00      1229    273           0    401       8      32
2016-09-01 23:40:00      1146    250           0    398       9      25
2016-09-01 23:41:00      1164    275           1    359       7      39
2016-09-01 23:42:00      1179    331           2    420       9      35
2016-09-01 23:43:00      1058    263           6    389       8      39
2016-09-01 23:44:00      1164    224           1    400       7      36
2016-09-01 23:45:00      1160    263           4    391       8      31
2016-09-01 23:46:00      1110    283           4    411      12      36
2016-09-01 23:47:00      1171    287           0    400      10      32
2016-09-01 23:48:00      1262    341           6    377       5      43
2016-09-01 23:49:00      1111    294           5    338       9      43
2016-09-01 23:50:00      1187    276           5    380      12      55
2016-09-01 23:51:00      1182    305           4    396      10      53
2016-09-01 23:52:00      1175    284           4    390      10      34
2016-09-01 23:53:00      1200    285           5    352      13      34
2016-09-01 23:54:00      1123    297           2    379      15      36
2016-09-01 23:55:00      1052    272           2    347      15      31
2016-09-01 23:56:00      1012    266           0    297       8      40
2016-09-01 23:57:00      1091    273           1    281       9      39
2016-09-01 23:58:00      1065    274           0    354      12      40
2016-09-01 23:59:00      1080    292           9    336      14      28
2016-09-02 00:00:00        19      5           0      4       0       2


type2               SPORTS   US USELECTION
time
2016-09-01 00:00:00    791   68          0
2016-09-01 00:01:00    773   48          1
2016-09-01 00:02:00    728   58          0
2016-09-01 00:03:00    723   54          2
2016-09-01 00:04:00    742   69          2
2016-09-01 00:05:00    672   70          1
2016-09-01 00:06:00    689   55          1
2016-09-01 00:07:00    692   61          1
2016-09-01 00:08:00    703   91          1
2016-09-01 00:09:00    662   63          1
2016-09-01 00:10:00    696   67          0
2016-09-01 00:11:00    639   67          0
2016-09-01 00:12:00    665   60          3
2016-09-01 00:13:00    675   76          0
2016-09-01 00:14:00    729   88          1
2016-09-01 00:15:00    691   94          0
2016-09-01 00:16:00    664   58          0
2016-09-01 00:17:00    705   62          1
2016-09-01 00:18:00    625   63          0
2016-09-01 00:19:00    661   79          1
2016-09-01 00:20:00    762   78          1
2016-09-01 00:21:00    806   67          0
2016-09-01 00:22:00    832   80          1
2016-09-01 00:23:00    785   80          1
2016-09-01 00:24:00    767   74          0
2016-09-01 00:25:00    763   75          1
2016-09-01 00:26:00    754   78          1
2016-09-01 00:27:00    630   54          0
2016-09-01 00:28:00    582   53          1
2016-09-01 00:29:00    611   88          0
...                    ...  ...        ...
2016-09-01 23:31:00    874   81          2
2016-09-01 23:32:00    903   88          2
2016-09-01 23:33:00    887  104          0
2016-09-01 23:34:00    943   80          0
2016-09-01 23:35:00    953   97          0
2016-09-01 23:36:00    947  104          2
2016-09-01 23:37:00    933  121          0
2016-09-01 23:38:00    827   87          0
2016-09-01 23:39:00    882   91          1
2016-09-01 23:40:00    903   93          1
2016-09-01 23:41:00    877   78          1
2016-09-01 23:42:00    893  104          0
2016-09-01 23:43:00    907   83          0
2016-09-01 23:44:00    907   88          0
2016-09-01 23:45:00    882   77          1
2016-09-01 23:46:00    897   62          2
2016-09-01 23:47:00    827   70          1
2016-09-01 23:48:00    920   89          1
2016-09-01 23:49:00    855   95          1
2016-09-01 23:50:00   1007   96          0
2016-09-01 23:51:00    924   70          2
2016-09-01 23:52:00    933   59          3
2016-09-01 23:53:00    945   63          1
2016-09-01 23:54:00    952   77          1
2016-09-01 23:55:00    836   65          0
2016-09-01 23:56:00    835  112          2
2016-09-01 23:57:00    847   89          1
2016-09-01 23:58:00    858   71          1
2016-09-01 23:59:00    775   76          2
2016-09-02 00:00:00     13    1          0

[1441 rows x 416 columns]