In [1]:
import pandas as pd
import numpy as np

In [14]:
sample = pd.read_csv('nextmag_tw_20160901', 
                     names = ['time','id1','location','name','user','type1','type2',
                              'type3','type4','ind','reading','device','from',
                'location2','view'],header = None, parse_dates = [0],
                    dtype = {'type4':str})

In [15]:
sample

,time,id1,location,name,user,type1,type2,type3,type4,ind,reading,device,from,location2,view
0,2016-09-01 02:43:34,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,43320162,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
1,2016-09-01 02:44:32,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
2,2016-09-01 02:47:29,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,POLITICS,REALTIME,POLITICS,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
3,2016-09-01 02:48:10,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,MOSTHIT,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
4,2016-09-01 05:54:47,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
5,2016-09-01 05:55:56,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,43322207,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
6,2016-09-01 05:56:23,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
7,2016-09-01 05:56:37,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,43321799,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
8,2016-09-01 05:56:47,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
9,2016-09-01 05:57:13,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,43321423,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
10,2016-09-01 05:58:18,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
11,2016-09-01 05:58:20,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,43321105,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
12,2016-09-01 05:58:25,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
13,2016-09-01 05:59:00,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,43318196,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
14,2016-09-01 05:59:04,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
15,2016-09-01 06:00:06,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,43313936,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
16,2016-09-01 06:00:41,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
17,2016-09-01 06:00:48,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,43313689,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
18,2016-09-01 06:01:00,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
19,2016-09-01 06:02:16,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,43308831,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,US,PAGEVIEW
20,2016-09-01 07:03:34,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,TW,PAGEVIEW
21,2016-09-01 07:03:53,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,TW,PAGEVIEW
22,2016-09-01 07:04:01,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,AUTO,REALTIME,CAR,0,0,MAGAZINE,iPhone,0,TW,PAGEVIEW
23,2016-09-01 07:04:10,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,43247646,AUTO,REALTIME,CAR,0,0,MAGAZINE,iPhone,0,TW,PAGEVIEW
24,2016-09-01 07:05:08,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,43247646,AUTO,REALTIME,CAR,0,0,MAGAZINE,iPhone,0,TW,PAGEVIEW
25,2016-09-01 07:05:11,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,AUTO,REALTIME,CAR,0,0,MAGAZINE,iPhone,0,TW,PAGEVIEW
26,2016-09-01 07:05:16,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,NEWS,REALTIME,LATEST,0,0,MAGAZINE,iPhone,0,TW,PAGEVIEW
27,2016-09-01 07:05:44,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,GADGETS,VIDEO,3C,0,0,MAGAZINE,iPhone,0,TW,PAGEVIEW
28,2016-09-01 07:06:09,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,GADGETS,VIDEO,3C,0,0,MAGAZINE,iPhone,0,TW,PAGEVIEW
29,2016-09-01 07:06:13,9f89c84a559f573636a47ff8daed0d33,TW,Next Magazine,0,AUTO,VIDEO,CAR,0,0,MAGAZINE,iPhone,0,TW,PAGEVIEW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1890665,2016-09-01 22:46:20,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43347067,ENTERTAIMENT,REALTIME,ENTERTAINMENT,0,0,MAGAZINE,Mobile Web,FACEBOOK,TW,PAGEVIEW
1890666,2016-09-01 22:54:12,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43341718,LIFE,REALTIME,LIFE,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890667,2016-09-01 22:57:06,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43339245,NEWS,REALTIME,NEWS,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890668,2016-09-01 22:57:13,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43343459,NEWS,REALTIME,NEWS,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890669,2016-09-01 23:01:37,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43341330,INTERNATIONAL,REALTIME,INTERNATIONAL,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890670,2016-09-01 23:02:47,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43321105,NEWS,REALTIME,NEWS,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890671,2016-09-01 23:02:53,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,35695204,NEWS,REALTIME,FEATURE,0,0,MAGAZINE,FBIA,FBIA,TW,PAGEVIEW
1890672,2016-09-01 23:03:48,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,34680986,FASHION,REALTIME,FASHION,0,0,MAGAZINE,Mobile Web,GOOGLE,TW,PAGEVIEW
1890673,2016-09-01 23:03:48,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43317163,NEWS,REALTIME,NEWS,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890674,2016-09-01 23:04:47,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,24274931,NEWS,REALTIME,NEWS,0,0,MAGAZINE,Mobile Web,GOOGLE,TW,PAGEVIEW
1890675,2016-09-01 23:06:22,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43343459,NEWS,REALTIME,NEWS,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890676,2016-09-01 23:08:33,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43253109,ENTERTAIMENT,MAGAZINE,ENTERTAINMENT,0,0,MAGAZINE,Mobile Web,GOOGLE,TW,PAGEVIEW
1890677,2016-09-01 23:18:17,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43234323,LIFE,REALTIME,LIFE,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890678,2016-09-01 23:18:39,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43254078,ENTERTAIMENT,REALTIME,ENTERTAINMENT,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890679,2016-09-01 23:18:53,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,19281356,FORUM,REALTIME,FORUM,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890680,2016-09-01 23:23:08,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43340775,ENTERTAIMENT,REALTIME,ENTERTAINMENT,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890681,2016-09-01 23:23:56,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,38137706,ENTERTAIMENT,REALTIME,ENTERTAIMENT,0,0,MAGAZINE,FBIA,FBIA,TW,PAGEVIEW
1890682,2016-09-01 23:24:18,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,0,NEWS,VIDEO,HOMEPAGE,0,0,MAGAZINE,Mobile Web,FACEBOOK,TW,PAGEVIEW
1890683,2016-09-01 23:24:57,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,38091476,HUMOR,REALTIME,FUN,0,0,MAGAZINE,FBIA,FBIA,TW,PAGEVIEW
1890684,2016-09-01 23:25:25,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43338349,NEWS,REALTIME,NEWS,0,0,MAGAZINE,Mobile Web,0,VN,PAGEVIEW
1890685,2016-09-01 23:27:42,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,32834255,0,0,0,0,0,MAGAZINE,FBIA,FBIA,TW,PAGEVIEW
1890686,2016-09-01 23:28:35,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,0,NEWS,VIDEO,HOMEPAGE,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890687,2016-09-01 23:30:59,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,23641085,LIFE,REALTIME,LIFE,0,0,MAGAZINE,Mobile Web,GOOGLE,TW,PAGEVIEW
1890688,2016-09-01 23:34:58,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,0,NEWS,MAGAZINE,HOMEPAGE,0,0,MAGAZINE,Web,GOOGLE,TW,PAGEVIEW
1890689,2016-09-01 23:35:12,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43276969,LIFE,MAGAZINE,HOMEPAGE,0,0,MAGAZINE,Web,0,TW,PAGEVIEW
1890690,2016-09-01 23:42:33,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,37882377,RELATIONSHIP,REALTIME,RELATIONSHIP,0,0,MAGAZINE,FBIA,FBIA,MY,PAGEVIEW
1890691,2016-09-01 23:43:18,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,42686544,LIFE,REALTIME,LIFE,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890692,2016-09-01 23:45:34,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,43344887,NEWS,REALTIME,NEWS,0,0,MAGAZINE,Mobile Web,0,TW,PAGEVIEW
1890693,2016-09-01 23:47:24,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,37882377,RELATIONSHIP,REALTIME,RELATIONSHIP,0,0,MAGAZINE,FBIA,FBIA,TW,PAGEVIEW
1890694,2016-09-01 23:52:52,d41d8cd98f00b204e9800998ecf8427e,TW,Next Magazine,31905263,NEWS,MAGAZINE,HOMEPAGE,0,0,MAGAZINE,Mobile Web,GOOGLE,TW,PAGEVIEW

In [5]:
sample.columns = ['time','id1','location','name','user','type1','type2','type3','type4','ind','reading','device','from',
                'location2','view']
# reset index as time
sample1 = sample.set_index('time')

In [6]:
# 1. Counting number of lines every minute
sample2 = sample1.resample('1T', how = {'id1':'count'})
sample2

                      id1
time
2016-09-01 00:00:00  1484
2016-09-01 00:01:00  1496
2016-09-01 00:02:00  1507
2016-09-01 00:03:00  1480
2016-09-01 00:04:00  1539
2016-09-01 00:05:00  1410
2016-09-01 00:06:00  1512
2016-09-01 00:07:00  1431
2016-09-01 00:08:00  1475
2016-09-01 00:09:00  1429
2016-09-01 00:10:00  1423
2016-09-01 00:11:00  1347
2016-09-01 00:12:00  1333
2016-09-01 00:13:00  1391
2016-09-01 00:14:00  1406
2016-09-01 00:15:00  1381
2016-09-01 00:16:00  1342
2016-09-01 00:17:00  1321
2016-09-01 00:18:00  1340
2016-09-01 00:19:00  1363
2016-09-01 00:20:00  1357
2016-09-01 00:21:00  1311
2016-09-01 00:22:00  1306
2016-09-01 00:23:00  1283
2016-09-01 00:24:00  1288
2016-09-01 00:25:00  1212
2016-09-01 00:26:00  1200
2016-09-01 00:27:00  1229
2016-09-01 00:28:00  1172
2016-09-01 00:29:00  1012
...                   ...
2016-09-01 23:31:00  1656
2016-09-01 23:32:00  1644
2016-09-01 23:33:00  1597
2016-09-01 23:34:00  1528
2016-09-01 23:35:00  1581
2016-09-01 23:36:00  1527
2016-09-01 23:37:00  1452
2016-09-01 23:38:00  1558
2016-09-01 23:39:00  1569
2016-09-01 23:40:00  1548
2016-09-01 23:41:00  1594
2016-09-01 23:42:00  1472
2016-09-01 23:43:00  1503
2016-09-01 23:44:00  1448
2016-09-01 23:45:00  1439
2016-09-01 23:46:00  1432
2016-09-01 23:47:00  1392
2016-09-01 23:48:00  1460
2016-09-01 23:49:00  1410
2016-09-01 23:50:00  1344
2016-09-01 23:51:00  1373
2016-09-01 23:52:00  1418
2016-09-01 23:53:00  1405
2016-09-01 23:54:00  1298
2016-09-01 23:55:00  1288
2016-09-01 23:56:00  1281
2016-09-01 23:57:00  1276
2016-09-01 23:58:00  1333
2016-09-01 23:59:00  1290
2016-09-02 00:00:00    23

[1441 rows x 1 columns]

In [7]:
# 2. Counting number of unique id1 every minute
sample3 = sample1.drop_duplicates(subset = {'id1'})
sample3 = sample3.resample('1T', how = {'id1':'count'})
sample3

                      id1
time
2016-09-01 00:00:00  1386
2016-09-01 00:01:00  1246
2016-09-01 00:02:00  1097
2016-09-01 00:03:00  1000
2016-09-01 00:04:00  1025
2016-09-01 00:05:00   890
2016-09-01 00:06:00   990
2016-09-01 00:07:00   915
2016-09-01 00:08:00   943
2016-09-01 00:09:00   899
2016-09-01 00:10:00   877
2016-09-01 00:11:00   834
2016-09-01 00:12:00   835
2016-09-01 00:13:00   853
2016-09-01 00:14:00   845
2016-09-01 00:15:00   831
2016-09-01 00:16:00   838
2016-09-01 00:17:00   802
2016-09-01 00:18:00   821
2016-09-01 00:19:00   834
2016-09-01 00:20:00   823
2016-09-01 00:21:00   782
2016-09-01 00:22:00   780
2016-09-01 00:23:00   752
2016-09-01 00:24:00   754
2016-09-01 00:25:00   690
2016-09-01 00:26:00   699
2016-09-01 00:27:00   735
2016-09-01 00:28:00   683
2016-09-01 00:29:00   633
...                   ...
2016-09-01 23:31:00   723
2016-09-01 23:32:00   702
2016-09-01 23:33:00   701
2016-09-01 23:34:00   645
2016-09-01 23:35:00   706
2016-09-01 23:36:00   656
2016-09-01 23:37:00   611
2016-09-01 23:38:00   642
2016-09-01 23:39:00   662
2016-09-01 23:40:00   662
2016-09-01 23:41:00   695
2016-09-01 23:42:00   636
2016-09-01 23:43:00   637
2016-09-01 23:44:00   606
2016-09-01 23:45:00   639
2016-09-01 23:46:00   599
2016-09-01 23:47:00   578
2016-09-01 23:48:00   590
2016-09-01 23:49:00   581
2016-09-01 23:50:00   571
2016-09-01 23:51:00   566
2016-09-01 23:52:00   570
2016-09-01 23:53:00   582
2016-09-01 23:54:00   566
2016-09-01 23:55:00   533
2016-09-01 23:56:00   537
2016-09-01 23:57:00   539
2016-09-01 23:58:00   543
2016-09-01 23:59:00   527
2016-09-02 00:00:00    10

[1441 rows x 1 columns]

In [8]:
# 3. pivoting table by type1
sample4 = sample.pivot_table(index = {'time'}, columns = {'type1'},aggfunc = 'count', fill_value = 0)
sample4 = sample4.resample('1T', how = 'sum')
sample4

                    id1                                                      \
type1                 0 AUTO ENTERTAIMENT ENTERTAINMENT ETW FASHION FEATURE
time
2016-09-01 00:00:00   1    1          181             0   1       4       0
2016-09-01 00:01:00   2    0          184             0   0       5       0
2016-09-01 00:02:00   0    0          187             0   2       0       0
2016-09-01 00:03:00   0    0          188             0   0       1       0
2016-09-01 00:04:00   0    1          207             0   2       1       0
2016-09-01 00:05:00   1    0          166             0   0       3       0
2016-09-01 00:06:00   0    0          202             0   0       1       0
2016-09-01 00:07:00   0    0          147             0   2       1       0
2016-09-01 00:08:00   0    0          182             0   0       5       0
2016-09-01 00:09:00   0    2          157             0   1       6       0
2016-09-01 00:10:00   1    0          150             0   2       3       0
2016-09-01 00:11:00   0    0          169             0   2       2       1
2016-09-01 00:12:00   0    1          173             0   3       2       0
2016-09-01 00:13:00   0    1          182             0   1       4       0
2016-09-01 00:14:00   0    0          169             0   3       1       0
2016-09-01 00:15:00   0    1          168             0   1       2       0
2016-09-01 00:16:00   0    0          177             0   1       3       0
2016-09-01 00:17:00   0    0          164             0   2       2       0
2016-09-01 00:18:00   0    0          150             0   4       1       0
2016-09-01 00:19:00   0    1          185             0   1       1       0
2016-09-01 00:20:00   0    0          152             0   0       8       0
2016-09-01 00:21:00   0    0          160             0   1       2       0
2016-09-01 00:22:00   0    0          149             0   2       2       0
2016-09-01 00:23:00   0    0          168             0   2       0       0
2016-09-01 00:24:00   1    0          147             0   1       3       0
2016-09-01 00:25:00   0    0          156             0   4       2       0
2016-09-01 00:26:00   0    0          179             0   3       2       0
2016-09-01 00:27:00   0    0          164             0   0       2       0
2016-09-01 00:28:00   0    0          172             0   2       2       0
2016-09-01 00:29:00   1    2          123             0   0       1       0
...                  ..  ...          ...           ...  ..     ...     ...
2016-09-01 23:31:00   0    0          226             0   6       6       0
2016-09-01 23:32:00   2    0          231             0   3       3       0
2016-09-01 23:33:00   1    0          251             0   1       4       0
2016-09-01 23:34:00   0    0          207             0   2       7       0
2016-09-01 23:35:00   1    0          232             0   2       4       0
2016-09-01 23:36:00   0    0          242             0   1       9       0
2016-09-01 23:37:00   0    0          227             0   3       6       0
2016-09-01 23:38:00   0    0          231             0   1       2       0
2016-09-01 23:39:00   1    0          220             0   1       5       0
2016-09-01 23:40:00   1    1          216             0   1       6       0
2016-09-01 23:41:00   0    0          244             0   1       6       0
2016-09-01 23:42:00   0    0          205             0   1       8       0
2016-09-01 23:43:00   0    0          223             0   2       2       0
2016-09-01 23:44:00   0    0          194             0   0       8       0
2016-09-01 23:45:00   0    0          229             0   1       6       0
2016-09-01 23:46:00   0    0          214             0   1       2       0
2016-09-01 23:47:00   0    0          219             0   4       5       0
2016-09-01 23:48:00   0    0          230             0   1      10       0
2016-09-01 23:49:00   2    0          217             0   3       2       0
2016-09-01 23:50:00   0    0          211             0   2      10       0
2016-09-01 23:51:00   0    1          205             0   3       2       0
2016-09-01 23:52:00   0    0          229             0   0       7       0
2016-09-01 23:53:00   0    0          228             0   1       5       0
2016-09-01 23:54:00   0    0          200             0   4       5       0
2016-09-01 23:55:00   0    0          224             0   0       4       0
2016-09-01 23:56:00   0    0          200             0   3       5       0
2016-09-01 23:57:00   0    0          196             0   4       2       0
2016-09-01 23:58:00   0    0          222             0   1       4       0
2016-09-01 23:59:00   0    0          210             0   1       5       0
2016-09-02 00:00:00   0    0            7             0   0       0       0

                                            ...      view                   \
type1               FINANCE FORUM GADGETS   ...   MYFAVOR NEWS PEOPLE PETS
time                                        ...
2016-09-01 00:00:00       5     3       0   ...         0  620      4    1
2016-09-01 00:01:00       3     2       1   ...         0  638      5    1
2016-09-01 00:02:00      13     1       0   ...         0  617     11    1
2016-09-01 00:03:00       2     1       0   ...         0  645      5    0
2016-09-01 00:04:00       9     1       0   ...         0  637      4    0
2016-09-01 00:05:00       5     0       0   ...         0  608      9    0
2016-09-01 00:06:00      13     1       1   ...         0  667      5    1
2016-09-01 00:07:00       4     1       0   ...         0  622      6    4
2016-09-01 00:08:00       6     1       0   ...         0  650      5    3
2016-09-01 00:09:00       9     1       0   ...         0  621      8    0
2016-09-01 00:10:00       9     2       2   ...         0  614      3    0
2016-09-01 00:11:00       5     2       2   ...         0  574      8    2
2016-09-01 00:12:00      10     0       0   ...         0  557      7    1
2016-09-01 00:13:00       8     0       1   ...         0  621      4    2
2016-09-01 00:14:00       5     1       1   ...         0  635      5    1
2016-09-01 00:15:00       3     2       3   ...         0  590      6    2
2016-09-01 00:16:00      12     2       4   ...         0  563      5    1
2016-09-01 00:17:00      10     1       2   ...         0  558      5    1
2016-09-01 00:18:00       8     0       1   ...         0  565     10    2
2016-09-01 00:19:00       4     3       1   ...         0  530      9    0
2016-09-01 00:20:00       3     1       0   ...         0  589     11    0
2016-09-01 00:21:00       6     0       1   ...         0  532      7    0
2016-09-01 00:22:00       8     0       1   ...         0  581     11    0
2016-09-01 00:23:00       8     0       0   ...         0  553      7    2
2016-09-01 00:24:00       8     2       1   ...         0  566     11    2
2016-09-01 00:25:00       8     1       0   ...         0  536      7    0
2016-09-01 00:26:00       9     2       1   ...         0  504      5    1
2016-09-01 00:27:00       5     1       1   ...         0  539     12    1
2016-09-01 00:28:00       7     0       0   ...         0  502      9    0
2016-09-01 00:29:00      10     1       0   ...         0  425      5    0
...                     ...   ...     ...   ...       ...  ...    ...  ...
2016-09-01 23:31:00     150     0       6   ...         0  759     40    1
2016-09-01 23:32:00     167     0      11   ...         0  744     40    0
2016-09-01 23:33:00     154     2       5   ...         0  700     32    1
2016-09-01 23:34:00     140     1       8   ...         0  696     31    0
2016-09-01 23:35:00     162     7      12   ...         0  656     39    1
2016-09-01 23:36:00     123     3      10   ...         0  655     34    0
2016-09-01 23:37:00     134     0       8   ...         0  643     26    0
2016-09-01 23:38:00     139     1       7   ...         0  705     27    0
2016-09-01 23:39:00     130     3       8   ...         1  734     29    0
2016-09-01 23:40:00     138     2       9   ...         1  693     39    0
2016-09-01 23:41:00     166     1       8   ...         0  697     23    0
2016-09-01 23:42:00     139     1      11   ...         0  644     24    1
2016-09-01 23:43:00     146     1       5   ...         0  667     27    0
2016-09-01 23:44:00     104     1      11   ...         1  668     33    0
2016-09-01 23:45:00     131     1      13   ...         0  617     24    0
2016-09-01 23:46:00     133     2      13   ...         0  635     27    0
2016-09-01 23:47:00     125     2       5   ...         0  604     28    0
2016-09-01 23:48:00     136     2       9   ...         0  627     27    0
2016-09-01 23:49:00     133     2      10   ...         0  591     38    0
2016-09-01 23:50:00     118     3       9   ...         0  589     25    0
2016-09-01 23:51:00     136     7       4   ...         0  607     26    0
2016-09-01 23:52:00     131     2       6   ...         0  610     23    0
2016-09-01 23:53:00     122     4      13   ...         0  604     26    1
2016-09-01 23:54:00     117     0       7   ...         0  543     25    0
2016-09-01 23:55:00     123     1       9   ...         0  528     12    0
2016-09-01 23:56:00      96     1       8   ...         0  579     32    1
2016-09-01 23:57:00     130     1       3   ...         0  533     28    1
2016-09-01 23:58:00     125     0      14   ...         0  541     32    1
2016-09-01 23:59:00     120     0      10   ...         0  529     23    0
2016-09-02 00:00:00       2     0       1   ...         0    8      0    0


type1               POLITICS RELATIONSHIP SETTING WATCH WINE YOUTUBE
time
2016-09-01 00:00:00        7           17       0     0    1       0
2016-09-01 00:01:00        4            6       0     0    0       0
2016-09-01 00:02:00        3           11       0     0    0       0
2016-09-01 00:03:00        5           13       0     0    0       0
2016-09-01 00:04:00        5           14       0     0    0       0
2016-09-01 00:05:00        6           13       0     1    0       0
2016-09-01 00:06:00        1           13       0     1    1       0
2016-09-01 00:07:00        6           21       0     0    0       0
2016-09-01 00:08:00        5            6       0     1    0       0
2016-09-01 00:09:00        5           14       0     0    0       0
2016-09-01 00:10:00        7           14       0     0    0       0
2016-09-01 00:11:00        2           11       0     0    0       0
2016-09-01 00:12:00        2            8       0     1    0       0
2016-09-01 00:13:00        2           10       0     1    0       0
2016-09-01 00:14:00        6            5       0     0    0       0
2016-09-01 00:15:00        5            8       0     1    0       0
2016-09-01 00:16:00        1            6       0     0    0       0
2016-09-01 00:17:00        8            6       0     1    0       0
2016-09-01 00:18:00        4            7       0     0    0       0
2016-09-01 00:19:00        2            9       1     0    1       0
2016-09-01 00:20:00        3            8       0     1    0       0
2016-09-01 00:21:00        1            6       0     0    0       1
2016-09-01 00:22:00        3           16       0     0    0       0
2016-09-01 00:23:00        0            9       0     0    0       0
2016-09-01 00:24:00        2           11       0     0    0       0
2016-09-01 00:25:00        5           10       0     0    0       1
2016-09-01 00:26:00        3           13       0     0    0       0
2016-09-01 00:27:00        2           11       0     1    0       2
2016-09-01 00:28:00        1           17       0     1    0       1
2016-09-01 00:29:00        4           13       0     0    0       0
...                      ...          ...     ...   ...  ...     ...
2016-09-01 23:31:00        3           10       0     0    0       0
2016-09-01 23:32:00        5           10       0     0    0       0
2016-09-01 23:33:00        6           11       0     1    0       0
2016-09-01 23:34:00        2           12       0     1    0       0
2016-09-01 23:35:00        6           11       0     0    0       0
2016-09-01 23:36:00        2           25       0     0    0       0
2016-09-01 23:37:00        2           12       0     0    0       0
2016-09-01 23:38:00        3           18       0     0    1       0
2016-09-01 23:39:00        2            9       0     0    0       0
2016-09-01 23:40:00        2           15       0     0    0       1
2016-09-01 23:41:00        2           12       0     0    0       1
2016-09-01 23:42:00        3           23       0     0    0       0
2016-09-01 23:43:00        1           14       0     0    0       0
2016-09-01 23:44:00        4           13       0     1    0       0
2016-09-01 23:45:00        4           17       0     0    0       0
2016-09-01 23:46:00        1           15       0     0    0       0
2016-09-01 23:47:00        3           16       0     0    0       0
2016-09-01 23:48:00        5           11       0     0    0       0
2016-09-01 23:49:00        2           16       0     0    0       0
2016-09-01 23:50:00        0           15       0     0    0       0
2016-09-01 23:51:00        3           15       0     0    1       0
2016-09-01 23:52:00        3            8       0     0    0       1
2016-09-01 23:53:00        4           11       0     0    0       0
2016-09-01 23:54:00        6           17       0     1    0       0
2016-09-01 23:55:00        1           10       0     0    0       0
2016-09-01 23:56:00        2           14       0     3    0       0
2016-09-01 23:57:00        2           18       0     3    0       0
2016-09-01 23:58:00        2           11       0     1    0       0
2016-09-01 23:59:00        2           12       0     0    0       0
2016-09-02 00:00:00        0            0       0     0    0       0

[1441 rows x 351 columns]

In [9]:
# 4. pivoting table by type2
sample5 = sample.pivot_table(index = {'time'}, columns = {'type2'},aggfunc = 'count', fill_value = 0).resample('1T', how = 'sum')
sample5

                    id1                                                  \
type2                 0 FANGROUP HOME IREPORT MAGAZINE MYFAVOR REALTIME
time
2016-09-01 00:00:00   1        0   14       0       30       0     1439
2016-09-01 00:01:00   2        0   23       0       12       0     1459
2016-09-01 00:02:00   0        0   11       0       22       0     1471
2016-09-01 00:03:00   0        0   17       0        9       0     1453
2016-09-01 00:04:00   0        0   18       0       20       0     1498
2016-09-01 00:05:00   1        0   15       1       21       0     1372
2016-09-01 00:06:00   0        0   16       0       28       0     1464
2016-09-01 00:07:00   0        0   15       1       32       0     1379
2016-09-01 00:08:00   0        0   29       0       22       0     1423
2016-09-01 00:09:00   0        0   18       0       14       0     1393
2016-09-01 00:10:00   1        0   21       0       16       0     1384
2016-09-01 00:11:00   0        0   20       0       22       0     1291
2016-09-01 00:12:00   0        0   17       0       18       0     1296
2016-09-01 00:13:00   0        0   13       0       24       0     1351
2016-09-01 00:14:00   0        0   19       0       14       0     1373
2016-09-01 00:15:00   0        0   18       0       15       0     1346
2016-09-01 00:16:00   0        0   13       0       20       0     1307
2016-09-01 00:17:00   0        0   20       0       17       0     1282
2016-09-01 00:18:00   0        0   13       0       26       0     1300
2016-09-01 00:19:00   0        0   12       0       24       0     1325
2016-09-01 00:20:00   0        0    9       0       18       0     1328
2016-09-01 00:21:00   0        0   16       0       26       0     1266
2016-09-01 00:22:00   0        0   17       0       22       0     1263
2016-09-01 00:23:00   0        0   16       0       22       0     1244
2016-09-01 00:24:00   1        0   13       2       25       0     1247
2016-09-01 00:25:00   0        0   14       0       15       0     1182
2016-09-01 00:26:00   0        0   14       0       25       0     1159
2016-09-01 00:27:00   0        0   18       0       25       0     1182
2016-09-01 00:28:00   0        1    9       0       12       0     1148
2016-09-01 00:29:00   1        1    9       0       19       0      982
...                  ..      ...  ...     ...      ...     ...      ...
2016-09-01 23:31:00   0        1   12       1       49       0     1587
2016-09-01 23:32:00   2        0   12       0       56       0     1569
2016-09-01 23:33:00   1        0   14       0       53       0     1526
2016-09-01 23:34:00   0        0   13       1       41       0     1470
2016-09-01 23:35:00   1        0   22       0       48       0     1508
2016-09-01 23:36:00   0        0   23       0       45       0     1459
2016-09-01 23:37:00   0        0   19       0       39       0     1394
2016-09-01 23:38:00   0        0   17       0       44       0     1496
2016-09-01 23:39:00   1        0   23       0       39       1     1502
2016-09-01 23:40:00   1        0   13       0       58       1     1470
2016-09-01 23:41:00   0        0   17       0       32       0     1543
2016-09-01 23:42:00   0        0   12       0       33       0     1427
2016-09-01 23:43:00   0        0   10       0       42       0     1446
2016-09-01 23:44:00   0        0   12       0       43       1     1390
2016-09-01 23:45:00   0        0   14       0       37       0     1383
2016-09-01 23:46:00   0        0   16       0       36       0     1379
2016-09-01 23:47:00   0        0   19       0       45       0     1324
2016-09-01 23:48:00   0        0   19       0       39       0     1394
2016-09-01 23:49:00   2        0   18       0       47       0     1336
2016-09-01 23:50:00   0        0   16       0       36       0     1291
2016-09-01 23:51:00   0        0    9       0       38       0     1320
2016-09-01 23:52:00   0        0   21       0       41       0     1346
2016-09-01 23:53:00   0        0   25       0       45       0     1333
2016-09-01 23:54:00   0        2   18       0       38       0     1234
2016-09-01 23:55:00   0        0   17       0       26       0     1240
2016-09-01 23:56:00   0        0   12       0       41       0     1226
2016-09-01 23:57:00   0        0   17       0       45       0     1212
2016-09-01 23:58:00   0        0   16       0       50       0     1260
2016-09-01 23:59:00   0        0    7       0       45       0     1237
2016-09-02 00:00:00   0        0    0       0        0       0       23

                                                ...         view               \
type2               SETTING VIDEO YOUTUBE_HK    ...     FANGROUP HOME IREPORT
time                                            ...
2016-09-01 00:00:00       0     0          0    ...            0   14       0
2016-09-01 00:01:00       0     0          0    ...            0   23       0
2016-09-01 00:02:00       0     3          0    ...            0   11       0
2016-09-01 00:03:00       0     1          0    ...            0   17       0
2016-09-01 00:04:00       0     3          0    ...            0   18       0
2016-09-01 00:05:00       0     0          0    ...            0   15       1
2016-09-01 00:06:00       0     4          0    ...            0   16       0
2016-09-01 00:07:00       0     4          0    ...            0   15       1
2016-09-01 00:08:00       0     1          0    ...            0   29       0
2016-09-01 00:09:00       0     4          0    ...            0   18       0
2016-09-01 00:10:00       0     1          0    ...            0   21       0
2016-09-01 00:11:00       0    14          0    ...            0   20       0
2016-09-01 00:12:00       0     2          0    ...            0   17       0
2016-09-01 00:13:00       0     3          0    ...            0   13       0
2016-09-01 00:14:00       0     0          0    ...            0   19       0
2016-09-01 00:15:00       0     2          0    ...            0   18       0
2016-09-01 00:16:00       0     2          0    ...            0   13       0
2016-09-01 00:17:00       0     2          0    ...            0   20       0
2016-09-01 00:18:00       0     1          0    ...            0   13       0
2016-09-01 00:19:00       1     1          0    ...            0   12       0
2016-09-01 00:20:00       0     2          0    ...            0    9       0
2016-09-01 00:21:00       0     2          0    ...            0   16       0
2016-09-01 00:22:00       0     4          0    ...            0   17       0
2016-09-01 00:23:00       0     1          0    ...            0   16       0
2016-09-01 00:24:00       0     0          0    ...            0   13       2
2016-09-01 00:25:00       0     0          0    ...            0   14       0
2016-09-01 00:26:00       0     2          0    ...            0   14       0
2016-09-01 00:27:00       0     2          0    ...            0   18       0
2016-09-01 00:28:00       0     1          0    ...            1    9       0
2016-09-01 00:29:00       0     0          0    ...            1    9       0
...                     ...   ...        ...    ...          ...  ...     ...
2016-09-01 23:31:00       0     6          0    ...            1   12       1
2016-09-01 23:32:00       0     5          0    ...            0   12       0
2016-09-01 23:33:00       0     3          0    ...            0   14       0
2016-09-01 23:34:00       0     3          0    ...            0   13       1
2016-09-01 23:35:00       0     2          0    ...            0   22       0
2016-09-01 23:36:00       0     0          0    ...            0   23       0
2016-09-01 23:37:00       0     0          0    ...            0   19       0
2016-09-01 23:38:00       0     1          0    ...            0   17       0
2016-09-01 23:39:00       0     3          0    ...            0   23       0
2016-09-01 23:40:00       0     4          1    ...            0   13       0
2016-09-01 23:41:00       0     1          1    ...            0   17       0
2016-09-01 23:42:00       0     0          0    ...            0   12       0
2016-09-01 23:43:00       0     5          0    ...            0   10       0
2016-09-01 23:44:00       0     2          0    ...            0   12       0
2016-09-01 23:45:00       0     5          0    ...            0   14       0
2016-09-01 23:46:00       0     1          0    ...            0   16       0
2016-09-01 23:47:00       0     4          0    ...            0   19       0
2016-09-01 23:48:00       0     8          0    ...            0   19       0
2016-09-01 23:49:00       0     7          0    ...            0   18       0
2016-09-01 23:50:00       0     1          0    ...            0   16       0
2016-09-01 23:51:00       0     6          0    ...            0    9       0
2016-09-01 23:52:00       0     9          1    ...            0   21       0
2016-09-01 23:53:00       0     2          0    ...            0   25       0
2016-09-01 23:54:00       0     6          0    ...            2   18       0
2016-09-01 23:55:00       0     5          0    ...            0   17       0
2016-09-01 23:56:00       0     2          0    ...            0   12       0
2016-09-01 23:57:00       0     2          0    ...            0   17       0
2016-09-01 23:58:00       0     7          0    ...            0   16       0
2016-09-01 23:59:00       0     1          0    ...            0    7       0
2016-09-02 00:00:00       0     0          0    ...            0    0       0

                                                                        \
type2               MAGAZINE MYFAVOR REALTIME SETTING VIDEO YOUTUBE_HK
time
2016-09-01 00:00:00       30       0     1439       0     0          0
2016-09-01 00:01:00       12       0     1459       0     0          0
2016-09-01 00:02:00       22       0     1471       0     3          0
2016-09-01 00:03:00        9       0     1453       0     1          0
2016-09-01 00:04:00       20       0     1498       0     3          0
2016-09-01 00:05:00       21       0     1372       0     0          0
2016-09-01 00:06:00       28       0     1464       0     4          0
2016-09-01 00:07:00       32       0     1379       0     4          0
2016-09-01 00:08:00       22       0     1423       0     1          0
2016-09-01 00:09:00       14       0     1393       0     4          0
2016-09-01 00:10:00       16       0     1384       0     1          0
2016-09-01 00:11:00       22       0     1291       0    14          0
2016-09-01 00:12:00       18       0     1296       0     2          0
2016-09-01 00:13:00       24       0     1351       0     3          0
2016-09-01 00:14:00       14       0     1373       0     0          0
2016-09-01 00:15:00       15       0     1346       0     2          0
2016-09-01 00:16:00       20       0     1307       0     2          0
2016-09-01 00:17:00       17       0     1282       0     2          0
2016-09-01 00:18:00       26       0     1300       0     1          0
2016-09-01 00:19:00       24       0     1325       1     1          0
2016-09-01 00:20:00       18       0     1328       0     2          0
2016-09-01 00:21:00       26       0     1266       0     2          0
2016-09-01 00:22:00       22       0     1263       0     4          0
2016-09-01 00:23:00       22       0     1244       0     1          0
2016-09-01 00:24:00       25       0     1247       0     0          0
2016-09-01 00:25:00       15       0     1182       0     0          0
2016-09-01 00:26:00       25       0     1159       0     2          0
2016-09-01 00:27:00       25       0     1182       0     2          0
2016-09-01 00:28:00       12       0     1148       0     1          0
2016-09-01 00:29:00       19       0      982       0     0          0
...                      ...     ...      ...     ...   ...        ...
2016-09-01 23:31:00       49       0     1587       0     6          0
2016-09-01 23:32:00       56       0     1569       0     5          0
2016-09-01 23:33:00       53       0     1526       0     3          0
2016-09-01 23:34:00       41       0     1470       0     3          0
2016-09-01 23:35:00       48       0     1508       0     2          0
2016-09-01 23:36:00       45       0     1459       0     0          0
2016-09-01 23:37:00       39       0     1394       0     0          0
2016-09-01 23:38:00       44       0     1496       0     1          0
2016-09-01 23:39:00       39       1     1502       0     3          0
2016-09-01 23:40:00       58       1     1470       0     4          1
2016-09-01 23:41:00       32       0     1543       0     1          1
2016-09-01 23:42:00       33       0     1427       0     0          0
2016-09-01 23:43:00       42       0     1446       0     5          0
2016-09-01 23:44:00       43       1     1390       0     2          0
2016-09-01 23:45:00       37       0     1383       0     5          0
2016-09-01 23:46:00       36       0     1379       0     1          0
2016-09-01 23:47:00       45       0     1324       0     4          0
2016-09-01 23:48:00       39       0     1394       0     8          0
2016-09-01 23:49:00       47       0     1336       0     7          0
2016-09-01 23:50:00       36       0     1291       0     1          0
2016-09-01 23:51:00       38       0     1320       0     6          0
2016-09-01 23:52:00       41       0     1346       0     9          1
2016-09-01 23:53:00       45       0     1333       0     2          0
2016-09-01 23:54:00       38       0     1234       0     6          0
2016-09-01 23:55:00       26       0     1240       0     5          0
2016-09-01 23:56:00       41       0     1226       0     2          0
2016-09-01 23:57:00       45       0     1212       0     2          0
2016-09-01 23:58:00       50       0     1260       0     7          0
2016-09-01 23:59:00       45       0     1237       0     1          0
2016-09-02 00:00:00        0       0       23       0     0          0


type2               YOUTUBE_TW
time
2016-09-01 00:00:00          0
2016-09-01 00:01:00          0
2016-09-01 00:02:00          0
2016-09-01 00:03:00          0
2016-09-01 00:04:00          0
2016-09-01 00:05:00          0
2016-09-01 00:06:00          0
2016-09-01 00:07:00          0
2016-09-01 00:08:00          0
2016-09-01 00:09:00          0
2016-09-01 00:10:00          0
2016-09-01 00:11:00          0
2016-09-01 00:12:00          0
2016-09-01 00:13:00          0
2016-09-01 00:14:00          0
2016-09-01 00:15:00          0
2016-09-01 00:16:00          0
2016-09-01 00:17:00          0
2016-09-01 00:18:00          0
2016-09-01 00:19:00          0
2016-09-01 00:20:00          0
2016-09-01 00:21:00          1
2016-09-01 00:22:00          0
2016-09-01 00:23:00          0
2016-09-01 00:24:00          0
2016-09-01 00:25:00          1
2016-09-01 00:26:00          0
2016-09-01 00:27:00          2
2016-09-01 00:28:00          1
2016-09-01 00:29:00          0
...                        ...
2016-09-01 23:31:00          0
2016-09-01 23:32:00          0
2016-09-01 23:33:00          0
2016-09-01 23:34:00          0
2016-09-01 23:35:00          0
2016-09-01 23:36:00          0
2016-09-01 23:37:00          0
2016-09-01 23:38:00          0
2016-09-01 23:39:00          0
2016-09-01 23:40:00          0
2016-09-01 23:41:00          0
2016-09-01 23:42:00          0
2016-09-01 23:43:00          0
2016-09-01 23:44:00          0
2016-09-01 23:45:00          0
2016-09-01 23:46:00          0
2016-09-01 23:47:00          0
2016-09-01 23:48:00          0
2016-09-01 23:49:00          0
2016-09-01 23:50:00          0
2016-09-01 23:51:00          0
2016-09-01 23:52:00          0
2016-09-01 23:53:00          0
2016-09-01 23:54:00          0
2016-09-01 23:55:00          0
2016-09-01 23:56:00          0
2016-09-01 23:57:00          0
2016-09-01 23:58:00          0
2016-09-01 23:59:00          0
2016-09-02 00:00:00          0

[1441 rows x 143 columns]